# Generated by Django 4.1 on 2024-03-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("time_tracking", "0003_alter_timeentry_options"),
        ("financial_tracking", "0006_alter_budgetingamount_target_definition"),
        ("habit_tracking", "0008_alter_habit_frequency"),
        ("task_management", "0003_alter_task_progress_status_on_closure_and_more"),
        ("core", "0005_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="budget_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="financial_tracking.budgetingperiod",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_management.task",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="time_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="time_tracking.timeentry",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habit_tracking.habit",
            ),
        ),
    ]
