# Generated by Django 4.1 on 2024-03-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="business_value",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=5,
            ),
        ),
    ]
