# Generated by Django 4.1 on 2024-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_management", "0002_alter_task_business_value_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress_status_on_closure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("skipped", "Skipped"),
                    ("done", "Done"),
                    ("parked", "Parked"),
                ],
                default="parked",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="repeat_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("daily_workdays", "WeekDays Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=20,
            ),
        ),
    ]
