# Generated by Django 4.1 on 2024-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_management", "0004_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="external_links",
            field=models.TextField(blank=True, null=True),
        ),
    ]
