# Generated by Django 4.1 on 2024-03-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "habit_tracking",
            "0003_alter_habit_end_date_alter_habit_progress_evaluation_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="goal_duration",
            new_name="daily_goal_duration",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="goal_numeric",
            new_name="daily_goal_numeric",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="monthly_goal",
            new_name="monthly_goal_numeric",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="single_time_goal",
            new_name="single_time_goal_numeric",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="weekly_goal",
            new_name="weekly_goal_numeric",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="yearly_goal",
            new_name="yearly_goal_numeric",
        ),
        migrations.AddField(
            model_name="habit",
            name="monthly_goal_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="single_time_goal_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="weekly_goal_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="yearly_goal_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
    ]
