# Generated by Django 4.1 on 2024-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracking", "0005_habitlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitlog",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
