# Generated by Django 4.1 on 2024-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracking", "0006_alter_habitlog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitlog",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
