# Generated by Django 4.1 on 2024-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracking", "0007_alter_habitlog_completion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("daily_workdays", "WeekDays Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
    ]
