# Generated by Django 4.1 on 2024-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("time_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="date",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
