# Generated by Django 4.1 on 2024-03-26 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("time_tracking", "0002_timeentry_date_alter_timeentry_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeentry",
            options={
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
            },
        ),
    ]
