# Generated by Django 4.1 on 2024-03-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank_account", "Bank Account"),
                    ("payables_account", "Payables Account"),
                    ("fixed_assets", "Fixed Assets"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
