# Generated by Django 4.1 on 2024-03-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial_tracking",
            "0004_account_user_contact_user_transaction_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetingamount",
            name="budget_period",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="financial_tracking.budgetingperiod",
            ),
            preserve_default=False,
        ),
    ]
