# Generated by Django 4.1 on 2024-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_tracking", "0005_budgetingamount_budget_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetingamount",
            name="target_definition",
            field=models.CharField(
                choices=[
                    ("at_least", "At least"),
                    ("less_than", "Less than"),
                    ("exactly", "Exactly"),
                    ("any_value", "Any value"),
                ],
                default="at_least",
                max_length=20,
            ),
        ),
    ]
