# Generated by Django 4.2.13 on 2024-06-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('default_activity', models.CharField(choices=[('NEW', 'NEW'), ('DELETE', 'DELETE'), ('MARK AS READ', 'MARK AS READ')], max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=999)),
                ('setting_value', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=9999, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('DELETED', 'DELETED'), ('MARKED AS READ', 'MARKED AS READ')], default='NEW', max_length=999)),
                ('auto_generated_category', models.CharField(blank=True, max_length=999, null=True)),
                ('auto_generated_summary', models.TextField(blank=True, null=True)),
                ('auto_generated_blog_ideas', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_cleaner.contact')),
            ],
        ),
    ]
